name: Build and push new version

on:
  push:
    tags:
      - "*.*.*"  # e.g. 2.3.10
      - "*.*-*"  # e.g. 2.4-dev17

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build
        run: IMAGE_TAG=${GITHUB_REF##*/} ./build.sh
